# 阶段训练通用配置
stage1:
  agent: ppo_1layer
  env: f16_goal_point
  total_timesteps: 15_000_000
  eval_freq: 10000
  log_root: "./experiments/goal_point"
  seed: 42
  num_cpu: 1
  model_num: -1  # -1表示对手模型输入随机

