# 阶段训练通用配置
stage1:
  stage_num: 1
  agent: ppo_1layer
  env: f16_tracking_stage1
  total_timesteps: 100_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8


stage2:
  stage_num: 2
  agent: ppo_1layer
  env: f16_tracking_stage2
  total_timesteps: 10000_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

# 阶段训练通用配置
stage3:
  stage_num: 1
  agent: ppo_1layer
  env: f16_tracking_stage1
  total_timesteps: 200_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

stage4:
  stage_num: 2
  agent: ppo_1layer
  env: f16_tracking_stage2
  total_timesteps: 10000_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

# 阶段训练通用配置
stage5:
  stage_num: 1
  agent: ppo_1layer
  env: f16_tracking_stage1
  total_timesteps: 300_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

stage6:
  stage_num: 2
  agent: ppo_1layer
  env: f16_tracking_stage2
  total_timesteps: 10000_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

# 阶段训练通用配置
stage7:
  stage_num: 1
  agent: ppo_1layer
  env: f16_tracking_stage1
  total_timesteps: 400_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

stage8:
  stage_num: 2
  agent: ppo_1layer
  env: f16_tracking_stage2
  total_timesteps: 10000_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

# 阶段训练通用配置
stage9:
  stage_num: 1
  agent: ppo_1layer
  env: f16_tracking_stage1
  total_timesteps: 500_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

stage10:
  stage_num: 2
  agent: ppo_1layer
  env: f16_tracking_stage2
  total_timesteps: 10000_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

# 阶段训练通用配置
stage11:
  stage_num: 1
  agent: ppo_1layer
  env: f16_tracking_stage1
  total_timesteps: 600_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

stage12:
  stage_num: 2
  agent: ppo_1layer
  env: f16_tracking_stage2
  total_timesteps: 10000_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

# 阶段训练通用配置
stage13:
  stage_num: 1
  agent: ppo_1layer
  env: f16_tracking_stage1
  total_timesteps: 700_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8

stage14:
  stage_num: 2
  agent: ppo_1layer
  env: f16_tracking_stage2
  total_timesteps: 10000_000
  eval_freq: 10000
  log_root: "./experiments"
  seed: 42
  num_cpu: 8