# 环境配置
plane: "C172"
task: "TrajectoryTask"
shape: "Shaping.EXTRA"
render_mode: null  # 训练时关闭渲染
use_vec_normalize: True
norm_obs: True
norm_reward: True
clip_obs: 10.0

wrappers:
  - name: "src.environments.ContinueWrapper:ContinueObservation"
    kwargs:
      skip_frame: 2
      total_frame: 10